# Generated by Django 5.0.10 on 2024-12-30 21:54

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_tags"),
    ]
    operations = [TrigramExtension()]
